# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19fbf064f2d40f8d85d5eac466e9212a635276fb479b395deb15f4bae6af1afe185ed15ad1289971e33a317c2166ef0506b13545363d286260a4ff151a3a545d

test:
  secret_key_base: 4117baf4a11033c07de94fa20a7d2aa3ad6a8b500bade18d4b6a840befedc7fe3faeca1c2dd23f158726a89247af8507b571d1e0ff0e343c999dfac4add0a533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
